
sudo: required
language: java

jdk:
  - openjdk8

script:
  - mvn clean compile assembly:single

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/build-test-conflicts/javaparser/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-ce73feac8db5b262311ef2f519a7ab3c34d7c101
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
            